name: "svelte-ds-app-launchpad/chromatic"
on:
  pull_request:
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/svelte/ds-global/**
      - packages/svelte/ds-app-launchpad/**
  push:
    branches:
      - main
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/svelte/ds-global/**
      - packages/svelte/ds-app-launchpad/**
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_SVELTE_DS_APP_LAUNCHPAD }}
    with:
      working-directory: packages/svelte/ds-app-launchpad
      externals: '[
        "configs/storybook/**",
        "packages/ds-assets/**",
        "packages/tokens/**",
        "packages/styles/**",
        "packages/utils/**",
        "packages/svelte/ds-global/**"
      ]'