name: "react-ds-global-form/chromatic"
on:
  pull_request:
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-global/**
      - packages/react/ds-global-form/**
  push:
    branches:
      - main
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-global/**
      - packages/react/ds-global-form/**
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_DS_GLOBAL_FORM }}
    with:
      working-directory: packages/react/ds-global-form
      externals: '[
        "configs/storybook/**",
        "packages/ds-assets/**",
        "packages/tokens/**",
        "packages/styles/**",
        "packages/utils/**",
        "packages/react/ds-global/**"
      ]'