name: "ds-react-core/Publish to chromatic"
on:
  pull_request:
    paths: [packages/react/ds-core/**]
defaults:
  run:
    working-directory: packages/react/ds-core
jobs:
  test-compile:
    uses: ./.github/workflows/_chromatic.yaml
    secrets:
      PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_DS_CORE_FORM }}
    with:
      working-directory: packages/react/ds-core
