name: "webcomponents-ds-global/chromatic"
on:
  pull_request:
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/webcomponents/ds-global/**
  push:
    branches:
      - main
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/webcomponents/ds-global/**
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_WEBCOMPONENTS_DS_GLOBAL }}
    with:
      working-directory: packages/webcomponents/ds-global
      externals: '[
        "configs/storybook/**",
        "packages/ds-assets/**",
        "packages/tokens/**",
        "packages/styles/**",
        "packages/utils/**"
      ]'