name: "react-boilerplate-vite/chromatic"
on:
  pull_request:
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-global/**
      - apps/react/boilerplate-vite/**
  push:
    branches:
      - main
    paths:
      - configs/storybook/**
      - packages/ds-assets/**
      - packages/tokens/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-global/**
      - apps/react/boilerplate-vite/**
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_BOILERPLATE_VITE }}
    with:
      working-directory: apps/react/boilerplate-vite
      externals: '[
        "configs/storybook/**",
        "packages/ds-assets/**",
        "packages/tokens/**",
        "packages/styles/**",
        "packages/utils/**",
        "packages/react/ds-global/**"
      ]'
