name: "react-ds-core-form/chromatic"
on:
  pull_request:
    paths:
      - configs/storybook/**
      - configs/typescript-base/**
      - configs/typescript-react/**
      - packages/styles/**
      - packages/utils/**
      - packages/react/ds-core/**
      - packages/react/ds-core-form/**
env:
  externalPaths:
    - configs/storybook/**
    - configs/typescript-base/**
    - configs/typescript-react/**
    - packages/styles/**
    - packages/utils/**
    - packages/react/ds-core/**
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_DS_CORE_FORM }}
    with:
      working-directory: packages/react/ds-core-form
      externals: ${{ toJSON(env.externalPaths) }}